### ISSUE TITLE
Age-specific survival

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/nordcansurvival#29]
Investigate age-groups to be used (both ICCS + new Nordic), and make priority (Siri/Nordcan)

**Comment by CotterpinDoozer** [comment]
This task is in progress.

**Comment by BjarteAAGNES** [comment]
first version: 

https://gitlab.kreftregisteret.no/nordcan/nordcansurvival/-/commit/46481cab60e3525271e0c0f686067ee0474eb84a

(some minor changes to the final export of csv, including n,  may be neccessary)

**Comment by BjarteAAGNES** [comment]
First version implemented.
