### ISSUE TITLE
first case of the entity/group to be analyzed

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/nordcansurvival#31]
On survival: The pat should be followed from the first case of the entity/group to be analyzed. This selection is done in extract_define_survival_data on the provided data . But, is it  ALSO taken care of in the preparation - using cases for all years back in time as basis for defining "first", thus defining a "global first" not dependent on when the survival analysis start?

WHEN ALL COUNTRIES HAVE DATA FROM 1969 THIS SHOULD NOT BE A MAJOR PROBLEM. (COULD HAVE MINOR IMPACT ON ESTIMATES THE FIRST 5/10 YEAR PERIOD - BUT PRESENTATION COULD BE RESTRICTED TO LAST 40 YEAS IF NECESSARY)

**Comment by CotterpinDoozer** [comment]
Issue: first case of the entity/group to be analyzed
Huidong comment: Bjarte will take this task.
