### ISSUE TITLE
hard coded year in extract_define_survival_data.ado

### ISSUE THREAD

**Issue by BjarteAAGNES** [CancerRegistryOfNorway/nordcansurvival#48]
TBD: For future discussion (not for this spring): should this information be hard-coded? 

https://github.com/CancerRegistryOfNorway/nordcansurvival/commit/edb5c9c9ddcdbd9c1bc39906bf1f94398d96809a

**Comment by CotterpinDoozer** [comment]
Issue: hard coded year in extract_define_survival_data.ado
Huidong comment: I think Bjarte will change the Stata code in next Spring.

**Comment by BjarteAAGNES** [comment]
For spring-23 the max year was set to 2022.
